"""v3.6 deal_round

Revision ID: 0ccbaaa1c59d
Revises: abf7b2ca6a9a
Create Date: 2025-11-09 08:25:19.406457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ccbaaa1c59d'
down_revision: Union[str, Sequence[str], None] = 'abf7b2ca6a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
