import { req, login, sellerLogin } from './lib/client.mjs';
const ts = Date.now().toString(36);
const bRes = await req('POST', '/buyers/', { email: 'otest_'+ts+'@t.com', password: 'Test1234!', name: 'OT'+ts.slice(0,8), nickname: 'OT'+ts.slice(0,8) });
const loginR = await login('otest_'+ts+'@t.com', 'Test1234!');
const token = loginR.data?.access_token;
const buyerId = bRes.data?.id;
const dRes = await req('POST', '/deals/', { product_name: '오퍼테스트딜', desired_qty: 50, target_price: 300000, creator_id: buyerId }, token);
const dealId = dRes.data?.id;
console.log('deal:', dRes.status, 'id='+dealId);
const biz = 'OTS'+ts.slice(0,8);
const sRes = await req('POST', '/sellers/', { email: 's_otest_'+ts+'@t.com', password: 'Test1234!', business_name: biz, nickname: biz, business_number: '123-45-67890', phone: '010-1111-2222', address: '서울', zip_code: '06234', established_date: '2020-01-01T00:00:00' });
const sellerId = sRes.data?.id;
await req('POST', '/sellers/'+sellerId+'/approve');
const slR = await sellerLogin('s_otest_'+ts+'@t.com', 'Test1234!');
const sellerToken = slR.data?.access_token;
console.log('seller:', sellerId, 'hasToken:', String(!!sellerToken), 'loginStatus:', slR.status);
const oRes = await req('POST', '/offers', { deal_id: dealId, seller_id: sellerId, price: 280000, total_available_qty: 50, shipping_mode: 'INCLUDED', shipping_fee_per_reservation: 0, shipping_fee_per_qty: 0 }, sellerToken);
console.log('offer status:', oRes.status);
console.log('offer data keys:', JSON.stringify(Object.keys(oRes.data || {})));
console.log('offer id:', oRes.data?.id, '| offer_id:', oRes.data?.offer_id);
console.log('offer data:', JSON.stringify(oRes.data).slice(0,400));
